### ISSUE TITLE
'barby/outputter/rmagick_outputter' crashes with ImageMagick 6.9.11-0

### ISSUE THREAD

**Issue by btihen** [toretore/barby#103]
**Installed**
macos 10.15.3
gem install barby 0.6.8
brew install ImageMagick 6.9.11-0

**On loading:**
require 'barby'
require 'barby/barcode/code_128'
require 'barby/barcode/code_93'
require 'barby/barcode/ean_13'
require 'barby/outputter/ascii_outputter' 
require 'barby/outputter/rmagick_outputter'  # crashes here on loading

**SUMMARY CRASH**
```
$ RAILS_ENV=development bundle exec rake db:migrate
rake aborted!

This installation of RMagick was configured with ImageMagick 6.9.10 but ImageMagick 6.9.11-0 is in use.

/Users/wti0405/devel/garaio-rem/rem2/lib/tasks/barcode_tester.rake:7:in `<top (required)>'
/Users/wti0405/devel/garaio-rem/rem2/Rakefile:14:in `<top (required)>'
/Users/wti0405/.rbenv/versions/2.5.3/bin/bundle:23:in `load'
/Users/wti0405/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

**DETAILED CRASH INFO**
```
$ RAILS_ENV=development bundle exec rake db:migrate --trace
rake aborted!

This installation of RMagick was configured with ImageMagick 6.9.10 but ImageMagick 6.9.11-0 is in use.
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rmagick-4.0.0/lib/rmagick_internal.rb:22:in `<top (required)>'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rmagick-4.0.0/lib/rmagick.rb:1:in `<top (required)>'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/barby-0.6.8/lib/barby/outputter/rmagick_outputter.rb:2:in `<top (required)>'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/Users/wti0405/devel/garaio-rem/rem2/lib/tasks/barcode_tester.rake:7:in `<top (required)>'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeus-0.15.14/lib/zeus/load_tracking.rb:82:in `load'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeus-0.15.14/lib/zeus/load_tracking.rb:82:in `load'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/zeus-0.15.14/lib/zeus/load_tracking.rb:74:in `load'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/engine.rb:658:in `each'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/engine.rb:658:in `run_tasks_blocks'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/application.rb:452:in `run_tasks_blocks'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/engine.rb:453:in `load_tasks'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `public_send'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `method_missing'
/Users/wti0405/devel/garaio-rem/rem2/Rakefile:14:in `<top (required)>'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/rake_module.rb:29:in `load'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:703:in `raw_load_rakefile'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:104:in `block in load_rakefile'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:103:in `load_rakefile'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:82:in `block in run'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/wti0405/.rbenv/versions/2.5.3/bin/rake:23:in `load'
/Users/wti0405/.rbenv/versions/2.5.3/bin/rake:23:in `<top (required)>'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `load'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:74:in `kernel_load'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli/exec.rb:28:in `run'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:463:in `exec'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:27:in `dispatch'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler/cli.rb:18:in `start'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/wti0405/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/Users/wti0405/.rbenv/versions/2.5.3/bin/bundle:23:in `load'
/Users/wti0405/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'

```

**Comment by btihen** [comment]
OOps - sorry solution is with rmagick gem reinstall -- not with barby:

```
gem uninstall rmagick
bundle install
```
